Repository input-output-hk/marlowe-cardano, pull requests merged in 2023-06, with the labels that each got.

#572 IOGX Integration [Work In Progress]
  .github/workflows/__iogx__/nightly.yml
  .github/workflows/__iogx__/test.yml
  .github/workflows/deploy.yml
  __iogx__/haskell-project.nix
  __iogx__/marlowe-cardano/bitte/default.nix
  __iogx__/marlowe-cardano/bitte/node-socat.nix
  __iogx__/marlowe-cardano/bitte/node/default.nix
  __iogx__/marlowe-cardano/compose-spec.nix
  __iogx__/marlowe-cardano/deploy/README.md
  __iogx__/marlowe-cardano/deploy/nomadTasks.nix
  __iogx__/marlowe-cardano/deploy/oci-images.nix
  __iogx__/marlowe-cardano/deploy/operables.nix
  __iogx__/marlowe-cardano/networks.nix
  __iogx__/marlowe-cardano/scripts.nix
  __iogx__/per-system-outputs.nix
  __iogx__/shell-module.nix
  dev-shell.nix
  flake.lock
  flake.nix
  hydra-jobs.nix
  marlowe/Language.Marlowe.Scripts.uplc47178-0.flat
  marlowe/Language.Marlowe.Scripts.uplc47178-1.flat
  marlowe/Language.Marlowe.Scripts.uplc47178-2.flat
  marlowe/Language.Marlowe.Scripts.uplc47178-3.flat
  marlowe/Language.Marlowe.Scripts.uplc47178-4.flat
  nix/tullia.nix
  packages.nix
Labels: No Changelog Required

#593 PLT-6117 Fixed erroneous option for `marlowe-proxy` in operables.
  deploy/nomadTasks.nix
  deploy/operables.nix
  nix/dev/compose.nix
Labels: No Changelog Required

#596 Improve test performance
  marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs
  marlowe-test/src/Spec/Marlowe/Plutus/Arbitrary.hs
  marlowe-test/src/Spec/Marlowe/Plutus/Specification.hs
  marlowe-test/src/Spec/Marlowe/Plutus/Transaction.hs
  marlowe-test/src/Spec/Marlowe/Plutus/Value.hs
  marlowe-test/src/Spec/Marlowe/Reference.hs
Labels: No Changelog Required

#598 PLT-5271 Withdraw Tests
  marlowe-apps/src/Language/Marlowe/Runtime/App/Build.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runtime/Interpret.hs
  marlowe-client/src/Control/Monad/Trans/Marlowe/Class.hs
  marlowe-integration-tests/marlowe-integration-tests.cabal
  marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Withdraw.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/IntegrationSpec.hs
  marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Withdraw.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
  marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
  marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/CommandSpec.hs
  marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
  marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
Labels: No Changelog Required

#601 PLT-6141 Revised resource recommendations.
  marlowe-runtime/doc/resources.md
Labels: documentation, No Changelog Required

#612 Remove leftover nix legacy file
  __iogx__/marlowe-cardano/compose-spec.nix
  flake.lock
Labels: No Changelog Required

#613 Change URL for IOGX flake
  flake.lock
  flake.nix
Labels: No Changelog Required

#620 Fix docker compose marlowe version
  nix/marlowe-cardano/compose.nix
Labels: No Changelog Required

#623 Add re-up to enterShell to generate compose.yaml
  flake.lock
  flake.nix
  nix/marlowe-cardano/scripts.nix
  nix/shell-module.nix
Labels: No Changelog Required

#602 PLT-3146 - GET /contracts/:contractId/next
  .gitignore
  hie.yaml
  marlowe-integration-tests/marlowe-integration-tests.cabal
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/ApplyInputs.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Common.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Get.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Next/Get.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Post.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Put.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Get.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Get.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Get.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Post.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Put.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Withdrawal/Post.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Withdrawal/Put.hs
  marlowe-integration-tests/test/Language/Marlowe/Runtime/WebSpec.hs
  marlowe-runtime-web/changelog.d/20230614_130059_nicolas.henin.md
  marlowe-runtime-web/marlowe-runtime-web.cabal
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts/Next.hs
  marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
  marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
  marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Next/Schema.hs
  marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Orphans.hs
  marlowe-runtime-web/test/Spec.hs
  marlowe-test/marlowe-test.cabal
  marlowe-test/src/Spec/Marlowe/Semantics.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Arbitrary.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Common/Isomorphism.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Common/QuickCheck.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Common/Tuple.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/Generator.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/When.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/When/Choice.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/When/Deposit.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/When/Notify.hs
  marlowe/changelog.d/20230614_130347_nicolas.henin.md
  marlowe/marlowe-cardano.cabal
  marlowe/src/Language/Marlowe/Core/V1/Next.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Applicables.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Applicables/Bound.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Applicables/CanChoose.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Applicables/CanDeposit.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Applicables/CanNotify.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/CanReduce.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/Indexed.hs
  marlowe/src/Language/Marlowe/Core/V1/Next/IsMerkleizedContinuation.hs
  marlowe/src/Language/Marlowe/Core/V1/Plate.hs
  marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
  marlowe/src/Language/Marlowe/Pretty.hs
  marlowe/src/Language/Marlowe/Scripts.hs
Labels: enhancement, semantics, Marlowe Runtime

#619 Bump IOGX v2.0
  .hindent.yaml
  .hlint.yaml
  .ignore
  .readthedocs.yml
  .stylish-haskell.yaml
  .tidyoperators
  .tidyrc.json
  flake.lock
  flake.nix
  fourmolu.yaml
  nix/haskell-project.nix
  nix/hydra-jobs.nix
  nix/iogx-config.nix
  nix/marlowe-cardano/bitte/default.nix
  nix/marlowe-cardano/bitte/node-socat.nix
  nix/marlowe-cardano/bitte/node/default.nix
  nix/marlowe-cardano/deploy/operables.nix
  nix/marlowe-cardano/integration-tests.nix
  nix/marlowe-cardano/networks.nix
  nix/marlowe-cardano/scripts.nix
  nix/per-system-outputs.nix
  nix/pre-commit-check.nix
  nix/shell-module.nix
  nix/shell.nix
Labels: No Changelog Required

#626 Fix Hlint issues and enable pre-commit checks in CI
  eventuo11y-extras/src/Control/Monad/Event/Class.hs
  eventuo11y-extras/src/Observe/Event/Backend/Extra.hs
  hie.yaml
  libs/aeson-via-serialise/src/Data/Aeson/ViaSerialise.hs
  libs/plutus-ledger-ada/src/Plutus/V1/Ledger/Ada.hs
  libs/plutus-ledger-aeson/src/Plutus/V1/Ledger/Aeson.hs
  libs/plutus-ledger-aeson/src/PlutusTx/Builtins/Aeson.hs
  marlowe-apps/finder/Main.hs
  marlowe-apps/oracle/Main.hs
  marlowe-chain-sync/marlowe-chain-indexer/Main.hs
  marlowe-chain-sync/marlowe-chain-sync/Main.hs
  marlowe-cli/cli-test/Contrib/Data/Aeson/Generic.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/CLI/Interpret.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/CLI/Monad.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/CLI/Types.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Contract.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Contract/ParametrizedMarloweJSON.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Contract/Source.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/ExecutionMode.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Interpret.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/InterpreterError.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Log.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Operation/Aeson.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runtime/Monitor.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/TestCase.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Wallet/Interpret.hs
  marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Wallet/Types.hs
  marlowe-cli/command/Language/Marlowe/CLI/Command/Test.hs
  marlowe-cli/src/Language/Marlowe/CLI/Merkle.hs
  marlowe-cli/src/Language/Marlowe/CLI/Types.hs
  marlowe-contracts/src/Marlowe/Contracts/Forward.hs
  marlowe-contracts/src/Marlowe/Contracts/Swap.hs
  marlowe-contracts/src/Marlowe/Contracts/Trivial.hs
  marlowe-contracts/src/Marlowe/Contracts/UTC/Forward.hs
  marlowe-contracts/src/Marlowe/Contracts/ZeroCouponBond.hs
  marlowe-contracts/test/Spec/Marlowe/Analysis.hs
  marlowe-integration/src/Test/Integration/Marlowe/Local.hs
  marlowe-protocols/src/Network/Protocol/ChainSeek/Server.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/Monad.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Withdrawals.hs
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
  marlowe-runtime/contract-api/Language/Marlowe/Protocol/Load/Client.hs
  marlowe-runtime/contract-api/Language/Marlowe/Protocol/Load/Types.hs
  marlowe-runtime/contract/Language/Marlowe/Runtime/Contract.hs
  marlowe-runtime/marlowe-contract/Main.hs
  marlowe-runtime/marlowe-indexer/Main.hs
  marlowe-runtime/marlowe-proxy/Main.hs
  marlowe-runtime/marlowe-runtime/Main.hs
  marlowe-runtime/marlowe-sync/Main.hs
  marlowe-runtime/marlowe-tx/Main.hs
  marlowe-runtime/proxy/Language/Marlowe/Runtime/Proxy.hs
  marlowe-runtime/sync/Language/Marlowe/Runtime/Sync.hs
  marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Golden.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract.hs
  marlowe-test/src/Spec/Marlowe/Semantics/Next/Contract/When/Choice.hs
  nix/hydra-jobs.nix
Labels: No Changelog Required

#628 Bump IOGX (introduces fourmolu 0.12.0.0)
  flake.lock
  flake.nix
  nix/haskell-project.nix
Labels: No Changelog Required

#631 Connect to chain sync query port with traced client
  marlowe-runtime/marlowe-runtime.cabal
  marlowe-runtime/marlowe-sync/Logging.hs
  marlowe-runtime/marlowe-sync/Main.hs
Labels: No Changelog Required

#634 Connect to chain sync query port with traced client
  marlowe-runtime/marlowe-sync/Main.hs
Labels: No Changelog Required

#635 use correct timestamps in status headers
  marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
Labels: No Changelog Required

#632 Bump IOGX
  flake.lock
  flake.nix
  nix/haskell-project.nix
  nix/hydra-jobs.nix
  nix/iogx-config.nix
  nix/pre-commit-check.nix
Labels: No Changelog Required

#642 Bump IOGX to bc5f588
  flake.lock
  flake.nix
  nix/haskell-project.nix
  nix/hydra-jobs.nix
  nix/iogx-config.nix
  nix/per-system-outputs.nix
  nix/pre-commit-check.nix
  nix/shell.nix
Labels: No Changelog Required

#647 PLT-6362 Added safety test for contract with prohibitive execution cost.
  marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs
Labels: No Changelog Required
