Repository input-output-hk/marlowe-cardano, pull requests merged in 2023-12, with the labels that each got.

#772 bump helm chart and using restored rds on QA
  deploy/marlowe-runtime/Chart.yaml
  deploy/marlowe-runtime/templates/chain-indexer.yaml
  deploy/marlowe-runtime/templates/chain-sync.yaml
  deploy/marlowe-runtime/templates/marlowe-contract.yaml
  deploy/marlowe-runtime/templates/marlowe-indexer.yaml
  deploy/marlowe-runtime/templates/marlowe-proxy.yaml
  deploy/marlowe-runtime/templates/marlowe-sync.yaml
  deploy/marlowe-runtime/templates/marlowe-tx.yaml
  deploy/marlowe-runtime/templates/marlowe-web-server.yaml
  deploy/marlowe-runtime/values.yaml
Labels: No Changelog Required

#773 using restored rds on Demo
  deploy/marlowe-runtime/values.yaml
Labels: No Changelog Required

#776 chore: increase cpu resource for indexer deployments
  deploy/marlowe-runtime/templates/chain-indexer.yaml
  deploy/marlowe-runtime/templates/chain-sync.yaml
Labels: No Changelog Required

#778 chore: adding k8s-update-strategy trait on marlowe-contract template
  deploy/marlowe-runtime/templates/marlowe-contract.yaml
Labels: No Changelog Required

#766 PLT-8703 Update documentation for open roles.
  marlowe-runtime/doc/open-roles.md
Labels: documentation, No Changelog Required

#781 PLT-3623 Re-measured Runtime resource requirements.
  marlowe-runtime/doc/resources.md
Labels: documentation, No Changelog Required

#755 Support aarch64-darwin Build
  cabal.project
  flake.lock
  flake.nix
  nix/__genesis-files__/byron-genesis-new.json
  nix/__genesis-files__/byron-genesis-old.json
  nix/__genesis-files__/shelley-genesis-new.json
  nix/__genesis-files__/shelley-genesis-old.json
  nix/marlowe-cardano/cardano-tools.nix
  nix/marlowe-cardano/integration-tests.nix
  nix/marlowe-cardano/networks.nix
  nix/marlowe-cardano/scriv.nix
  nix/outputs.nix
  nix/project.nix
  nix/shell.nix
Labels: No Changelog Required

#782 PLT-3623 Updated `marlowe-contract` resource measurements for testnets.
  marlowe-runtime/doc/resources.md
Labels: documentation, No Changelog Required

#786 PLT-9055 Published new `asData` validators.
  flake.lock
  marlowe-cli/tests/Spec/Analysis.hs
  marlowe-runtime/changelog.d/20231222_132417_brian.bush_PLT_9055.md
  marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs
  marlowe/scripts/marlowe-rolepayout.plutus
  marlowe/scripts/marlowe-semantics.plutus
  marlowe/scripts/open-role.plutus
  nix/marlowe-cardano/scripts.nix
Labels: Marlowe Validator

#790 Revert "PLT-9055 Published new `asData` validators."
  flake.lock
  marlowe-cli/tests/Spec/Analysis.hs
  marlowe-runtime/changelog.d/20231222_132417_brian.bush_PLT_9055.md
  marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs
  marlowe/scripts/marlowe-rolepayout.plutus
  marlowe/scripts/marlowe-semantics.plutus
  marlowe/scripts/open-role.plutus
  nix/marlowe-cardano/scripts.nix
Labels: No Changelog Required
